server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TomatoMall?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
          enabled: true
          max-file-size: 10MB
          max-request-size: 10MB


logging:
  level:
    org.springframework.security: DEBUG

aliyun:
  oss:
    endpoint: oss-cn-nanjing.aliyuncs.com
    accessKeyId: LTAI5t6hRmAjXfVN97hGxrmo
    accessKeySecret: hHqSjwUdpXKVdhIvhj3D1v8BJyEu6c
    bucketName: tomato-mall-milvelas

alipay:
  appId: 2021000147699442
  merchantPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCt+QuOG2wfpFJ2ScXzkqMyzjW74kPOls/osJsVWrXHCsUBQWYbqQlC5deP13162e1tDRrnfD6+Ekphi1KTid4fJrkxhr6yO2HCLNMzr/NY8B1huNC8Z4eOAF2vrX8XOLsfbJczGDUmj5axmbl2PPSg5nGo3s+C03OpmdciCJKueBme+t1nBoSfkXFMsnOumfdZaX3hLcYl/ioprk5mY4teXAFi1MJvVFPpR0vphJYjsSCmLnhj18YnSmHbfzA8pgAYqLT8D7eOuVs1CFl0fDhxFjx1KuvChivP0p8G41CV9kFymW5rM6san3QVxK31Gzrdy5g7GwkKHyPsmrzSN3dTAgMBAAECggEBAIVpMzxBuTO2nmoJftyfebkPO1OeWuNE8aD+NZ81lapSjuq8jSHvCaQcf6bV2GrqTdFPuG8F71Nw0UtmPOfZVNXMqz3Yl8o0EW6HU1sStelhERcMVD32opP5od6DjK9xGMYrTvOmv7OXbzc4rGmIqwvsTAL1AmrP3qWTzM9ThbB2MzEzouCmwcfl+j1/s6lBkFxnXhsG33lB3dKoQafdLZtYkXXi3hN/LWAKO4Cf/xDGfKgX2QBpMpiq7t0DAZ4C1uL8wHq0NXjU6zx2RGr0JXxH5FVlTNsGo0FukTAdKX/A4ZCf7vnSygVER+JSwMLZ90d3leYUb+6BBPHtG2zoYWECgYEA3CVV3m0+JFWN04CH+WdVxOTPULp6i/aRNg43D1jVz748YTbtyrD9KZS0wj9XFXbadzLrck5twU7y375aRnnun8GBk3DGQkAz84zVRays1jxpbBEGLrBnUTDMVLnLZ+opJxm8mr7+FGqvkr6GRKYmhTzSrOFv/Frx91v7tmzF87ECgYEAyk6XqkJLiiwYIjLeJqx8CEn9HwYlR8j7asKQIMUDcD6XYJFZWYCRBDjvc4m2WYE+KTcsLXE4EFZhbFfYlD2L2vMTktAgWvYXJ2q9c5GReJsvq8u1MV8E9e8TJ3DQhq05u2ftdc9mDAH95xqajt9Ls3eBFytDA2s+3NTonROPsEMCgYBnMfUzo9/qZlRqXajfx4nUFzH7dL63V2iwfy9eOVVY4aMqKvaC+j5iPHwTRl/LBwDXuX3XAl6+rAR7z54/xS6PosTb2ZSGP9RaiZz74TrP3lfIuZ49SqHT1F0kJkfsOT77PjxECd3OskgFMNx916jc8isLsU2ubO9Z9btjw09zsQKBgDUV7GxL2yCVs3t915dUWXOfXqE+bpfooDiCd2lx6RYSBozbdxOqTeNKwWKS91uDM3mDNb9y3yBCWmwgnP9BKyq38CHtJSBZRPgd5TqnLwHzzs2ItbIP2fBi3KbTzpQYbnbDrablVkS+XQ7Ah2AILggYyrH2sy35fVRbNfLJyEGbAoGATj0/GVtwE5K5+pBH0vemp4i2zU06z/igJg2hPADY5UZfMFfjNdZZaK+7zCktzFRw5cdQQfSQDW5pflbc/e9Uta+EwCjsq6d3vNQYdE82LPq/it9fKOwGXeDzRVu3M5H9S9bJ+qO+di1ei8qymj+Y22jaxN56ojMoz78xCpa+Yzk=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArfkLjhtsH6RSdknF85KjMs41u+JDzpbP6LCbFVq1xwrFAUFmG6kJQuXXj9d9etntbQ0a53w+vhJKYYtSk4neHya5MYa+sjthwizTM6/zWPAdYbjQvGeHjgBdr61/Fzi7H2yXMxg1Jo+WsZm5djz0oOZxqN7PgtNzqZnXIgiSrngZnvrdZwaEn5FxTLJzrpn3WWl94S3GJf4qKa5OZmOLXlwBYtTCb1RT6UdL6YSWI7Egpi54Y9fGJ0ph238wPKYAGKi0/A+3jrlbNQhZdHw4cRY8dSrrwoYrz9KfBuNQlfZBcpluazOrGp90FcSt9Rs63cuYOxsJCh8j7Jq80jd3UwIDAQAB
  notifyUrl: http://3gu7pt.natappfree.cc/api/alipay/notify
  returnUrl: http://member.zyz.com/memberOrder.html
  serverUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  signType: RSA2
  charset: utf-8
