server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TomatoMall?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Gwg7910081434
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.springframework.security: DEBUG

aliyun:
  oss:
    endpoint: oss-cn-nanjing.aliyuncs.com
    accessKeyId: LTAI5t6hRmAjXfVN97hGxrmo
    accessKeySecret: hHqSjwUdpXKVdhIvhj3D1v8BJyEu6c
    bucketName: bluewhale-milvelas